/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterFace;

import DAO.TaiKhoanDAO;
import Helper.MsgBox;
import Model.TaiKhoan;
import java.text.ParseException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLyTaiKhoanJInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyNhanVienJInternal
     */
    public QuanLyTaiKhoanJInternal() {
        initComponents();
        setMaximizable(true);
        fillToTable();

    }
    TaiKhoanDAO dao = new TaiKhoanDAO();
    DefaultTableModel modelProducts;

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblTaiKhoan.getModel();
        model.setRowCount(0);//clear table
        try {
            for (TaiKhoan tk : dao.getAllTaiKhoan()) {
                Object rowData[] = new Object[4];
                rowData[0] = tk.getMaNV();
                rowData[1] = tk.getTenTaiKhoan();
                rowData[2] = tk.getMatKhau();
                rowData[3] = tk.getVaiTro();
                model.addRow(rowData);
            }
        } catch (Exception e) {
            //e.printStackTrace();

        }
    }

    public void reset() {
        txtMaNhanVien.setText("");
        txtTenTK.setText("");
        txtMatKhau.setText("");

    }


    public TaiKhoan getModel() throws ParseException {
        TaiKhoan tk = new TaiKhoan();
        tk.setMaNV(txtMaNhanVien.getText());
        tk.setTenTaiKhoan(txtTenTK.getText());
        tk.setMatKhau(txtMatKhau.getText());
        tk.setVaiTro(rdoTruongPhong.isSelected());
        //tk.setVaiTro(rdoTruongPhong.isSelected() ? 1 : 0);
        //tk.setVaiTro(Integer.parseInt(txtVaiTro.getText()));

        return tk;
    }

    public void setModel(TaiKhoan tk) {
        txtMaNhanVien.setText(tk.getMaNV());
        txtTenTK.setText(tk.getTenTaiKhoan());
        txtMatKhau.setText(tk.getMatKhau());
        rdoTruongPhong.setSelected(tk.getVaiTro()==true);
        rdoNhanVien.setSelected(tk.getVaiTro()==false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdoTruongPhong = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();
        btnSeach = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("QUẢN LÝ TÀI KHOẢN");

        jLabel1.setText("Mã nhân viên: ");

        jLabel2.setText("Tên tài khoản: ");

        jLabel3.setText("Mật khẩu:");

        jLabel4.setText("Vai trò:");

        buttonGroup1.add(rdoTruongPhong);
        rdoTruongPhong.setText("Trưởng phòng");

        buttonGroup1.add(rdoNhanVien);
        rdoNhanVien.setText("Nhân viên");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Document.png"))); // NOI18N
        btnNew.setText("Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên tài khoản", "Mật khẩu", "Vai trò"
            }
        ));
        tblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTaiKhoan);

        btnSeach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        btnSeach.setText("Tìm kiếm");
        btnSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoTruongPhong)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                        .addComponent(rdoNhanVien))
                                    .addComponent(txtTenTK)
                                    .addComponent(txtMatKhau))))
                        .addGap(51, 51, 51)
                        .addComponent(btnSeach)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeach))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoTruongPhong)
                    .addComponent(rdoNhanVien))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnNew))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkForm() {
        if(txtMaNhanVien.getText().equals("")){
            MsgBox.alert(this, "Mã nhân viên không được để trống");
            return false;
        }
        if(txtTenTK.getText().equals("")){
            MsgBox.alert(this, "Tên tài khoản không được để trống");
            return false;
        }
        if(txtMatKhau.getPassword().equals("")){
            MsgBox.alert(this, "Mật khẩu không được để trống");
            return false;
        }
        return true;
    }
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (checkForm()) {
            try {
                TaiKhoan sv = getModel();
                if (dao.add(sv) > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                    fillToTable();
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm thất bại, mã nhân viên đã tồn tại");
            }
        } else {
            MsgBox.alert(this, "Bạn chưa nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (checkForm()) {
            try {
                TaiKhoan tk = getModel();
                if (dao.updateTaiKhoanByID(tk) > 0) {
                    MsgBox.alert(this, "Cập nhật thành công");
                    fillToTable();
                }
            } catch (Exception e) {
            }
        } else {
            MsgBox.alert(this, "Bạn chưa nhập thông tin");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtMaNhanVien.getText().isEmpty()) {
            MsgBox.alert(this, "Bạn chưa nhập mã nhân viên để xóa");
        } else {
            if (MsgBox.confirm(this, "Bạn chắc chắn muốn xóa?")) {
                if (dao.delTaiKhoanByID(txtMaNhanVien.getText()) > 0) {
                    MsgBox.alert(this, "Xóa thành công");
                    fillToTable();
                    reset();
                } else {
                    MsgBox.alert(this, "Sai mã nhân viên! Vui lòng nhập lại");
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        this.reset();
    }//GEN-LAST:event_btnNewActionPerformed

    private void tblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiKhoanMouseClicked
        try {
            int id = tblTaiKhoan.rowAtPoint(evt.getPoint());
            String manv = tblTaiKhoan.getValueAt(id, 0).toString();
            TaiKhoan tk = dao.getOneNhanVienByMaNV(manv);
            setModel(tk);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "Error: MouseClick" + e.getMessage());
            //e.printStackTrace();
        }
    }//GEN-LAST:event_tblTaiKhoanMouseClicked

    private void btnSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachActionPerformed
        if (txtMaNhanVien.getText().isEmpty()) {
            MsgBox.alert(this, "Bạn chưa nhập mã nhân viên");
        } else {
            TaiKhoan tk = dao.getOneNhanVienByMaNV(txtMaNhanVien.getText());
            if (tk != null) {
                TaiKhoan d = dao.getOneNhanVienByMaNV(tk.getMaNV());
                if (d != null) {
                    setModel(d);
                } else {
                    txtMaNhanVien.setText(tk.getMaNV());
                    txtTenTK.setText(tk.getTenTaiKhoan());
                    txtMatKhau.setText(tk.getMatKhau());
                    rdoTruongPhong.setSelected(tk.getVaiTro());
//                    rdoTruongPhong.setSelected(tk.getVaiTro() == 1);
                    rdoNhanVien.setSelected(tk.getVaiTro());
//                    rdoNhanVien.setSelected(tk.getVaiTro() == 0);
                }
            } else {
                MsgBox.alert(this, "Mã nhân viên không đúng");
            }
        }
    }//GEN-LAST:event_btnSeachActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoTruongPhong;
    private javax.swing.JTable tblTaiKhoan;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenTK;
    // End of variables declaration//GEN-END:variables
}
